name: Update BibTeX

on:
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  changed-files:
    name: changed-files
    runs-on: ubuntu-latest
    outputs:
      bib: ${{ steps.changed-files-yaml.outputs.bib_any_changed }}
      bib_changed_files: ${{ steps.changed-files-yaml.outputs.bib_all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            bib:
              - '**/*.bib'

  update-bib:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.bib == 'true' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install BibTeX parser
        run: |
          python -m pip install --pre bibtexparser
      - name: Merge BibTeX files
        run: |
          python merge_bib.py ${ALL_CHANGED_FILES}
        env:
            ALL_CHANGED_FILES: ${{ needs.changed-files.outputs.bib_changed_files }}
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Format bibtex files
        run: |
          npm install -g bibtex-tidy
          bibtex-tidy all.bib -m --curly --sort --blank-lines --sort-fields
      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
      - name: Read summary.log
        if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' }}
        id: summary
        uses: juliangruber/read-file-action@v1
        with:
          path: ./summary.log
      - name: Comment on pull request
        if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### BibTeX References Updated
            The BibTeX references have been updated. Here are the changes:
            ```
            ${{ steps.summary.outputs.content }}
            ```
